import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
import 'rxjs';
import * as jquery from 'jquery';
window['jQuery'] = jquery;
window['$'] = jquery;
